// Generated by CoffeeScript 1.6.2
(function() {
  define('helpers', function() {
    var Helpers;

    Helpers = (function() {
      function Helpers() {}

      Helpers.prototype.listenLinks = function() {
        return $(document.body).on('click', 'a', function(e) {
          var $it;

          e.preventDefault();
          $it = $(this).addClass('is-check');
          $it.hasClass('js-nav-link') && $('.js-nav-link').removeClass('is-check');
          $it.addClass('is-check');
          return App.router.navigate($it.attr('href'), {
            trigger: true
          });
        });
      };

      Helpers.prototype.normalizeBoolean = function(val) {
        return (val === 'false') !== (Boolean(val));
      };

      Helpers.prototype.unescape = function(str) {
        return str.replace(/\&lt;/g, '<').replace(/\&gt;/g, '>').replace(/\&quot;/g, '"');
      };

      return Helpers;

    })();
    return new Helpers;
  });

}).call(this);
