// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define('router', ['backbone', 'controllers/PagesController'], function(B, pc) {
    var Router, _ref;

    Router = (function(_super) {
      __extends(Router, _super);

      function Router() {
        _ref = Router.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      Router.prototype.routes = {
        '': 'main',
        'edit': 'edit'
      };

      Router.prototype.main = function() {
        return this.startPage(pc.main);
      };

      Router.prototype.edit = function() {
        return this.startPage(pc.edit);
      };

      Router.prototype.startPage = function(View) {
        return App.main.show(new View(this.o));
      };

      return Router;

    })(B.Router);
    return Router;
  });

}).call(this);
