// Generated by CoffeeScript 1.6.2
(function() {
  var Section, SectionSchema, app, express, http, io, mongo, path, port;

  express = require('express');

  http = require('http');

  port = 3000;

  mongo = require('mongoose');

  path = require('path');

  app = express();

  app.set('port', process.env.PORT || port);

  app.use(express.favicon(__dirname + '/frontend/favicon.ico'));

  app.use(express["static"](__dirname + '/frontend'));

  app.use(express.bodyParser());

  app.use(express.methodOverride());

  mongo.connect('mongodb://localhost/iconmelon');

  SectionSchema = new mongo.Schema({
    name: String,
    author: String,
    license: String,
    creationDate: String,
    icons: Array
  });

  Section = mongo.model('Section', SectionSchema);

  io = require('socket.io').listen(app.listen(process.env.PORT || port));

  io.sockets.on("connection", function(socket) {
    console.log('connected');
    return socket.on("sections:read", function(data, callback) {
      return Section.find({}, function(err, docs) {
        return callback(null, docs);
      });
    });
  });

}).call(this);
