// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define('collectionViews/FiltersCollectionView', ['collectionViews/ProtoCollectionView', 'views/FilterView'], function(ProtoView, FilterView) {
    var FiltersCollectionView, _ref;

    FiltersCollectionView = (function(_super) {
      __extends(FiltersCollectionView, _super);

      function FiltersCollectionView() {
        _ref = FiltersCollectionView.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      FiltersCollectionView.prototype.itemView = FilterView;

      FiltersCollectionView.prototype.template = '#filters-collection-view-template';

      FiltersCollectionView.prototype.initialize = function(o) {
        this.o = o != null ? o : {};
        FiltersCollectionView.__super__.initialize.apply(this, arguments);
        return this;
      };

      FiltersCollectionView.prototype.appendHtml = function(collectionView, itemView, i) {
        return this.$('#js-filters-place').append(itemView.el);
      };

      return FiltersCollectionView;

    })(ProtoView);
    return FiltersCollectionView;
  });

}).call(this);
