// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define('views/pages/terms', ['views/pages/PageView'], function(PageView) {
    var Terms, _ref;

    Terms = (function(_super) {
      __extends(Terms, _super);

      function Terms() {
        _ref = Terms.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      Terms.prototype.template = '#terms-page-template';

      Terms.prototype.className = 'terms-p';

      Terms.prototype.initialize = function() {
        console.log('init');
        Terms.__super__.initialize.apply(this, arguments);
        return this;
      };

      return Terms;

    })(PageView);
    return Terms;
  });

}).call(this);
