// Generated by CoffeeScript 1.6.2
(function() {
  define('controllers/PagesController', ['views/pages/main', 'views/pages/edit'], function(main, edit) {
    var Controller;

    Controller = (function() {
      function Controller() {
        this.main = main;
        this.edit = edit;
      }

      return Controller;

    })();
    return new Controller;
  });

}).call(this);
