// Generated by CoffeeScript 1.6.2
(function() {
  var _this = this,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define('collections/FiltersCollection', ['backbone', 'models/FilterModel'], function(B, FilterModel) {
    var FiltersCollection, _ref;

    FiltersCollection = (function(_super) {
      __extends(FiltersCollection, _super);

      function FiltersCollection() {
        _ref = FiltersCollection.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      FiltersCollection.prototype.model = FilterModel;

      FiltersCollection.prototype.url = 'filters';

      return FiltersCollection;

    })(B.Collection);
    return FiltersCollection;
  });

}).call(this);
