// Generated by CoffeeScript 1.6.2
(function() {
  var _this = this,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define('collections/SectionsCollection', ['backbone', 'models/SectionModel'], function(B, SectionModel) {
    var SectionsCollection, _ref;

    SectionsCollection = (function(_super) {
      __extends(SectionsCollection, _super);

      function SectionsCollection() {
        _ref = SectionsCollection.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      SectionsCollection.prototype.model = SectionModel;

      SectionsCollection.prototype.url = 'sections';

      return SectionsCollection;

    })(B.Collection);
    return SectionsCollection;
  });

}).call(this);
