// Generated by CoffeeScript 1.6.2
(function() {
  var _this = this,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define('collections/IconsCollection', ['backbone', 'models/IconModel'], function(B, IconModel) {
    var IconsCollection, _ref;

    IconsCollection = (function(_super) {
      __extends(IconsCollection, _super);

      function IconsCollection() {
        _ref = IconsCollection.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      IconsCollection.prototype.model = IconModel;

      return IconsCollection;

    })(B.Collection);
    return IconsCollection;
  });

}).call(this);
