// Generated by CoffeeScript 1.6.2
(function() {
  define('helpers', ['md5'], function(md5) {
    var Helpers;

    Helpers = (function() {
      function Helpers() {}

      Helpers.prototype.getRandom = function(min, max) {
        return Math.floor((Math.random() * ((max + 1) - min)) + min);
      };

      Helpers.prototype.listenLinks = function() {
        return $(document.body).on('click', 'a', function(e) {
          var $it;

          e.preventDefault();
          $it = $(this);
          return App.router.navigate($it.attr('href'), {
            trigger: true
          });
        });
      };

      Helpers.prototype.normalizeBoolean = function(val) {
        return (val === 'false') !== (Boolean(val));
      };

      Helpers.prototype.unescape = function(str) {
        return str != null ? str.replace(/\&lt;/g, '<').replace(/\&gt;/g, '>').replace(/\&quot;/g, '"') : void 0;
      };

      Helpers.prototype.generateHash = function() {
        return md5((new Date) + (new Date).getMilliseconds() + Math.random(9999999999999) + Math.random(9999999999999) + Math.random(9999999999999));
      };

      return Helpers;

    })();
    return new Helpers;
  });

}).call(this);
