// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define('router', ['backbone', 'controllers/PagesController'], function(B, pc) {
    var Router, _ref;

    Router = (function(_super) {
      __extends(Router, _super);

      function Router() {
        _ref = Router.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      Router.prototype.routes = {
        '': 'main',
        'submit': 'submit'
      };

      Router.prototype.main = function() {
        this.startPage(pc.main);
        return this.chechMainMenuItem();
      };

      Router.prototype.submit = function() {
        this.startPage(pc.submit);
        return this.chechMainMenuItem('#js-submit');
      };

      Router.prototype.startPage = function(View) {
        App.main.show(new View(this.o));
        return App.$bodyHtml.animate({
          'scrollTop': 0
        });
      };

      Router.prototype.chechMainMenuItem = function(selector) {
        return App.$mainHeader.find('a').removeClass('is-check').filter(selector).addClass('is-check');
      };

      return Router;

    })(B.Router);
    return Router;
  });

}).call(this);
