// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define('views/IconSelectView', ['views/ProtoView', 'collectionViews/SectionsCollectionView', 'collections/SectionsCollection', 'collectionViews/FiltersCollectionView', 'collections/FiltersCollection', 'underscore', 'jquery', 'helpers'], function(ProtoView, SectionsCollectionView, SectionsCollection, FiltersCollectionView, FiltersCollection, _, $, helpers) {
    var IconSelectView, _ref;

    IconSelectView = (function(_super) {
      __extends(IconSelectView, _super);

      function IconSelectView() {
        _ref = IconSelectView.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      IconSelectView.prototype.template = '#icon-select-view-template';

      IconSelectView.prototype.className = '';

      IconSelectView.prototype.events = {
        'keyup': 'filter'
      };

      IconSelectView.prototype.filter = function(e) {
        return App.vent.trigger('icon-select-filter:change', $.trim($(e.target).val()));
      };

      IconSelectView.prototype.initialize = function(o) {
        this.o = o != null ? o : {};
        this.buttonCounterTemplate = _.template(helpers.unescape($("#button-counter-template").text()));
        this.bindModelEvents();
        IconSelectView.__super__.initialize.apply(this, arguments);
        return this;
      };

      IconSelectView.prototype.bindModelEvents = function() {
        return this.model.on('change:selectedCounter', _.bind(this.renderButton, this));
      };

      IconSelectView.prototype.render = function() {
        var _this = this;

        IconSelectView.__super__.render.apply(this, arguments);
        this.renderButton();
        _.defer(function() {
          return _this.renderView();
        });
        return this;
      };

      IconSelectView.prototype.renderView = function() {
        var filter, filter2, filter3;

        filter2 = {
          hash: 'drop-shadow',
          name: 'drop shadow',
          iconHash: 'tick-icon'
        };
        filter = {
          hash: 'inset-shadow',
          name: 'inset shadow',
          iconHash: 'tick-icon'
        };
        filter3 = {
          hash: 'drop-shadow-color',
          name: 'drop shadow with color',
          iconHash: 'tick-icon'
        };
        this.filtersCollectionView = new FiltersCollectionView({
          collection: new FiltersCollection,
          isRender: true,
          $el: this.$('#js-filters-place')
        });
        this.filtersCollectionView.collection.fetch();
        this.sectionsCollectionView = new SectionsCollectionView({
          collection: new SectionsCollection,
          isRender: true,
          $el: this.$('#js-section-collections-place')
        });
        this.sectionsCollectionView.collection.fetch();
        App.sectionsCollectionView = this.sectionsCollectionView;
        this.model.sectionsView = this.sectionsCollectionView;
        return this;
      };

      IconSelectView.prototype.renderButton = function() {
        return this.$('.icon-set-l').replaceWith(this.buttonCounterTemplate(this.model.toJSON()));
      };

      return IconSelectView;

    })(ProtoView);
    return IconSelectView;
  });

}).call(this);
