// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define('views/ProtoView', ['marionette'], function(M) {
    var ProtoView, _ref;

    ProtoView = (function(_super) {
      __extends(ProtoView, _super);

      function ProtoView() {
        _ref = ProtoView.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      ProtoView.prototype.initialize = function(o) {
        this.o = o != null ? o : {};
        this.o.$el && this.setElement(this.o.$el);
        ProtoView.__super__.initialize.apply(this, arguments);
        this.o.isRender && this.render();
        return this;
      };

      ProtoView.prototype.render = function() {
        ProtoView.__super__.render.apply(this, arguments);
        return this;
      };

      ProtoView.prototype.teardown = function() {
        return this.undelegateEvents();
      };

      return ProtoView;

    })(M.ItemView);
    return ProtoView;
  });

}).call(this);
